name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: checkout code
      uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
       version: latest
    - name: login to docker hub
      run: docker login -u "quyetwru" -p "Az@741852"
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx build --push --file Dockerfile --tag quyetwru/udpxy:latest --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
    #- name: docker push
    #- name: Docker push
      #id: docker_build
      #uses: docker/build-push-action@v2
      #with:
      #  context: .
        #file: Dockerfile
        #platform: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      #  push: true
      #  tags: quyetwru/udpxy:latest
      #run: docker push quyetwru/udpxy
      #run: |
      #    docker buildx build --push \
      #      --tag registry-1.docker.io/quyetwru/udpxy:latest \
      #      --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
